# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: "Ryan Marcotte's .NET Programming Blog"
title_separator: "-"
subtitle: "Sharing guidance on software architecture and design."
name: "Ryan Marcotte"
email:
repository: "RyanMarcotte/ryanmarcotte.github.io"
github_username: RyanMarcotte
minimal_mistakes_skin: default
words_per_minute: 200 # Used to calculate the read time.
search: true

# Build settings
markdown: kramdown
highlighter: rouge # GitHub Pages currently (June 2019) only supports "rouge"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Canada/Saskatchewan" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ryan Marcotte"
  avatar : "/assets/images/bio-photo.jpg"
  location: "Regina, SK, Canada"
  bio    : "I solve business problems through people and technology.  I believe the best designs steer people into pits of success."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RyanMarcotte"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan-marcotte-a8a92a111/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RyanMarcotte"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan-marcotte-a8a92a111/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
