# https://docs.github.com/en/rest/pages?apiVersion=2022-11-28#request-a-github-pages-build
name: Refresh

# https://crontabkit.com/crontab-expression-generator
# at 9:30 AM, only on Sunday
on:
  schedule:
    - cron: '0 16 * * SUN'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/RyanMarcotte/ryanmarcotte.github.io/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}