# File: .github/workflows/refresh.yml
name: Refresh

# https://crontabkit.com/crontab-expression-generator
# at 9:30 AM, only on Sunday
on:
  schedule:
    - cron: '30 9 * * SUN'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
